version: "3.9"

services:
  api:
    container_name: robotsystem-api-prod
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./src/backend/.env.prod
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: robotsystem-postgres-prod
    image: postgres:16
    environment:
      POSTGRES_USER: user_prod
      POSTGRES_PASSWORD: password_prod
      POSTGRES_DB: robotsystem_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_prod:
