services:
  api:
    container_name: robotsystem-api-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./backend/.env.dev
    depends_on:
      - postgres


  postgres:
    container_name: robotsystem-postgres-dev
    image: postgres:16
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql+psycopg2://user_dev:password_dev@postgres:5432/robotsystem_dev
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: robotsystem_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
